# Generated by Django 5.0.6 on 2024-06-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('idade', models.IntegerField()),
                ('castracao', models.CharField(max_length=20)),
                ('saude', models.CharField(max_length=100)),
                ('pelagem', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='gatos')),
            ],
        ),
    ]
